package com.presto.api.order.entity;

import com.presto.common.dao.BaseEntity;
import java.math.BigDecimal;

/**
 * 续惜阅
 *
 * Auto Generated by <code>CodeGenerator</code>
 */
public class ContinueOrder extends BaseEntity {
    private static final long serialVersionUID = 1L;
    private Long userId;//
    private Long orderId;//
    private BigDecimal continueAmount;//续借金额总价
    private Integer continueDays;//续借天数

    /**
     * return 
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * @param userId 
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * return 
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * @param orderId 
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * return 续借金额总价
     */
    public BigDecimal getContinueAmount() {
        return continueAmount;
    }

    /**
     * @param continueAmount 续借金额总价
     */
    public void setContinueAmount(BigDecimal continueAmount) {
        this.continueAmount = continueAmount;
    }

    /**
     * return 续借天数
     */
    public Integer getContinueDays() {
        return continueDays;
    }

    /**
     * @param continueDays 续借天数
     */
    public void setContinueDays(Integer continueDays) {
        this.continueDays = continueDays;
    }
}