package com.presto.api.order.entity;

import com.presto.common.dao.BaseEntity;
import java.math.BigDecimal;
import java.util.List;
import java.util.Date;

/**
 * 订单头表
 *
 * Auto Generated by <code>CodeGenerator</code>
 */
public class Order extends BaseEntity {
    private static final long serialVersionUID = 1L;
    private Long userId;//
    private String address;//联系方式-地址
    private String mobile;//联系方式-电话
    private String name;//联系方式
    private Integer status;//订单状态:0-新建;10-待支付;20-待发货;30-配送中;40-惜阅中;50-待归还;
    transient private List<Integer> statuss;//订单状态:0-新建;10-待支付;20-待发货;30-配送中;40-惜阅中;50-待归还;
    private BigDecimal amount;//订单总价
    private Date dateFrom;//借阅日期从
    private Date dateEnd;//借阅日期到
    private Date orderDate;//下单日期
    private Date payDate;//支付日期
    private Date sendDate;//配送日期
    private String sendOrderCom;//配送公司
    private String sendOrderComOrderNo;//配送订单号
    private Date readingDate;//开始惜阅日期
    private Date backingDate;//待归还日期
    private Date doneDate;//订单完成日期
    private String note;//备注

    /**
     * return 
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * @param userId 
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * return 联系方式-地址
     */
    public String getAddress() {
        return address;
    }

    /**
     * @param address 联系方式-地址
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * return 联系方式-电话
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * @param mobile 联系方式-电话
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * return 联系方式
     */
    public String getName() {
        return name;
    }

    /**
     * @param name 联系方式
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * return 订单状态:0-新建;10-待支付;20-待发货;30-配送中;40-惜阅中;50-待归还;
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * @param status 订单状态:0-新建;10-待支付;20-待发货;30-配送中;40-惜阅中;50-待归还;
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * return 订单状态:0-新建;10-待支付;20-待发货;30-配送中;40-惜阅中;50-待归还;s
     */
    public List<Integer> getStatuss() {
        return statuss;
    }

    /**
     * @param statuss 订单状态:0-新建;10-待支付;20-待发货;30-配送中;40-惜阅中;50-待归还;
     */
    public void setStatuss(List<Integer> statuss) {
        this.statuss = statuss;
    }

    /**
     * return 订单总价
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * @param amount 订单总价
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * return 借阅日期从
     */
    public Date getDateFrom() {
        return dateFrom;
    }

    /**
     * @param dateFrom 借阅日期从
     */
    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }

    /**
     * return 借阅日期到
     */
    public Date getDateEnd() {
        return dateEnd;
    }

    /**
     * @param dateEnd 借阅日期到
     */
    public void setDateEnd(Date dateEnd) {
        this.dateEnd = dateEnd;
    }

    /**
     * return 下单日期
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * @param orderDate 下单日期
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    /**
     * return 支付日期
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * @param payDate 支付日期
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    /**
     * return 配送日期
     */
    public Date getSendDate() {
        return sendDate;
    }

    /**
     * @param sendDate 配送日期
     */
    public void setSendDate(Date sendDate) {
        this.sendDate = sendDate;
    }

    /**
     * return 配送公司
     */
    public String getSendOrderCom() {
        return sendOrderCom;
    }

    /**
     * @param sendOrderCom 配送公司
     */
    public void setSendOrderCom(String sendOrderCom) {
        this.sendOrderCom = sendOrderCom;
    }

    /**
     * return 配送订单号
     */
    public String getSendOrderComOrderNo() {
        return sendOrderComOrderNo;
    }

    /**
     * @param sendOrderComOrderNo 配送订单号
     */
    public void setSendOrderComOrderNo(String sendOrderComOrderNo) {
        this.sendOrderComOrderNo = sendOrderComOrderNo;
    }

    /**
     * return 开始惜阅日期
     */
    public Date getReadingDate() {
        return readingDate;
    }

    /**
     * @param readingDate 开始惜阅日期
     */
    public void setReadingDate(Date readingDate) {
        this.readingDate = readingDate;
    }

    /**
     * return 待归还日期
     */
    public Date getBackingDate() {
        return backingDate;
    }

    /**
     * @param backingDate 待归还日期
     */
    public void setBackingDate(Date backingDate) {
        this.backingDate = backingDate;
    }

    /**
     * return 订单完成日期
     */
    public Date getDoneDate() {
        return doneDate;
    }

    /**
     * @param doneDate 订单完成日期
     */
    public void setDoneDate(Date doneDate) {
        this.doneDate = doneDate;
    }

    /**
     * return 备注
     */
    public String getNote() {
        return note;
    }

    /**
     * @param note 备注
     */
    public void setNote(String note) {
        this.note = note;
    }
}