package com.presto.api.order.entity;

import com.presto.common.dao.BaseEntity;
import java.math.BigDecimal;

/**
 * 订单行表
 *
 * Auto Generated by <code>CodeGenerator</code>
 */
public class OrderDetail extends BaseEntity {
    private static final long serialVersionUID = 1L;
    private Long orderId;//
    private Long userBookId;//
    private BigDecimal price;//书籍价格

    /**
     * return 
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * @param orderId 
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * return 
     */
    public Long getUserBookId() {
        return userBookId;
    }

    /**
     * @param userBookId 
     */
    public void setUserBookId(Long userBookId) {
        this.userBookId = userBookId;
    }

    /**
     * return 书籍价格
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * @param price 书籍价格
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}