package com.presto.api.order.entity;

import com.presto.common.dao.BaseEntity;
import java.math.BigDecimal;
import java.util.List;
import java.util.Date;

/**
 * 订单头表
 *
 * Auto Generated by <code>CodeGenerator</code>
 */
public class Order extends BaseEntity {
    private static final long serialVersionUID = 1L;
    private Long userId;//
    private Integer status;//订单状态:0-新建；10-待支付;20-待发货;30-配送中;40-惜阅中;50-待归还;
    transient private List<Integer> statuss;//订单状态:0-新建；10-待支付;20-待发货;30-配送中;40-惜阅中;50-待归还;
    private BigDecimal amount;//订单总价
    private Date dateFrom;//借阅日期从
    private Date dateEnd;//借阅日期到
    private Date orderDate;//下单日期

    /**
     * return 
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * @param userId 
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * return 订单状态:0-新建；10-待支付;20-待发货;30-配送中;40-惜阅中;50-待归还;
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * @param status 订单状态:0-新建；10-待支付;20-待发货;30-配送中;40-惜阅中;50-待归还;
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * return 订单状态:0-新建；10-待支付;20-待发货;30-配送中;40-惜阅中;50-待归还;s
     */
    public List<Integer> getStatuss() {
        return statuss;
    }

    /**
     * @param statuss 订单状态:0-新建；10-待支付;20-待发货;30-配送中;40-惜阅中;50-待归还;
     */
    public void setStatuss(List<Integer> statuss) {
        this.statuss = statuss;
    }

    /**
     * return 订单总价
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * @param amount 订单总价
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * return 借阅日期从
     */
    public Date getDateFrom() {
        return dateFrom;
    }

    /**
     * @param dateFrom 借阅日期从
     */
    public void setDateFrom(Date dateFrom) {
        this.dateFrom = dateFrom;
    }

    /**
     * return 借阅日期到
     */
    public Date getDateEnd() {
        return dateEnd;
    }

    /**
     * @param dateEnd 借阅日期到
     */
    public void setDateEnd(Date dateEnd) {
        this.dateEnd = dateEnd;
    }

    /**
     * return 下单日期
     */
    public Date getOrderDate() {
        return orderDate;
    }

    /**
     * @param orderDate 下单日期
     */
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
}