package com.presto.api.order.entity;

import com.presto.common.dao.BaseEntity;

/**
 * 订单行表
 *
 * Auto Generated by <code>CodeGenerator</code>
 */
public class OrderDetail extends BaseEntity {
    private static final long serialVersionUID = 1L;
    private Long orderId;//
    private Long userBookId;//

    /**
     * return 
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * @param orderId 
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * return 
     */
    public Long getUserBookId() {
        return userBookId;
    }

    /**
     * @param userBookId 
     */
    public void setUserBookId(Long userBookId) {
        this.userBookId = userBookId;
    }
}