package com.presto.api.order.entity;

import com.presto.common.dao.BaseEntity;
import java.util.List;

/**
 * 还书表
 *
 * Auto Generated by <code>CodeGenerator</code>
 */
public class ReturnBook extends BaseEntity {
    private static final long serialVersionUID = 1L;
    private Long userId;//
    private Long orderId;//
    private Integer status;//订单状态:0-新建;10-确认收到;20-未收到
    transient private List<Integer> statuss;//订单状态:0-新建;10-确认收到;20-未收到
    private String deliveryCom;//快递公司
    private String deliveryOrderNo;//快递单号

    /**
     * return 
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * @param userId 
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * return 
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * @param orderId 
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * return 订单状态:0-新建;10-确认收到;20-未收到
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * @param status 订单状态:0-新建;10-确认收到;20-未收到
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * return 订单状态:0-新建;10-确认收到;20-未收到s
     */
    public List<Integer> getStatuss() {
        return statuss;
    }

    /**
     * @param statuss 订单状态:0-新建;10-确认收到;20-未收到
     */
    public void setStatuss(List<Integer> statuss) {
        this.statuss = statuss;
    }

    /**
     * return 快递公司
     */
    public String getDeliveryCom() {
        return deliveryCom;
    }

    /**
     * @param deliveryCom 快递公司
     */
    public void setDeliveryCom(String deliveryCom) {
        this.deliveryCom = deliveryCom;
    }

    /**
     * return 快递单号
     */
    public String getDeliveryOrderNo() {
        return deliveryOrderNo;
    }

    /**
     * @param deliveryOrderNo 快递单号
     */
    public void setDeliveryOrderNo(String deliveryOrderNo) {
        this.deliveryOrderNo = deliveryOrderNo;
    }
}