package com.presto.api.user.entity;

import com.presto.common.dao.BaseEntity;
import java.math.BigDecimal;

/**
 * 用户余额账户明细
 *
 * Auto Generated by <code>CodeGenerator</code>
 */
public class AccountDetail extends BaseEntity {
    private static final long serialVersionUID = 1L;
    private Long accountId;//
    private Integer sourceType;//明细来源:0-微信充值;1-订单支付
    private Long sourceTypeId;//明细来源id
    private BigDecimal amount;//金额

    /**
     * return 
     */
    public Long getAccountId() {
        return accountId;
    }

    /**
     * @param accountId 
     */
    public void setAccountId(Long accountId) {
        this.accountId = accountId;
    }

    /**
     * return 明细来源:0-微信充值;1-订单支付
     */
    public Integer getSourceType() {
        return sourceType;
    }

    /**
     * @param sourceType 明细来源:0-微信充值;1-订单支付
     */
    public void setSourceType(Integer sourceType) {
        this.sourceType = sourceType;
    }

    /**
     * return 明细来源id
     */
    public Long getSourceTypeId() {
        return sourceTypeId;
    }

    /**
     * @param sourceTypeId 明细来源id
     */
    public void setSourceTypeId(Long sourceTypeId) {
        this.sourceTypeId = sourceTypeId;
    }

    /**
     * return 金额
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * @param amount 金额
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
}