package com.presto.api.user.entity;

import com.presto.common.dao.BaseEntity;
import java.util.List;

/**
 * 用户余额账户
 *
 * Auto Generated by <code>CodeGenerator</code>
 */
public class Account extends BaseEntity {
    private static final long serialVersionUID = 1L;
    private Long userId;//
    private Integer status;//状态:0-正常
    transient private List<Integer> statuss;//状态:0-正常

    /**
     * return 
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * @param userId 
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * return 状态:0-正常
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * @param status 状态:0-正常
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * return 状态:0-正常s
     */
    public List<Integer> getStatuss() {
        return statuss;
    }

    /**
     * @param statuss 状态:0-正常
     */
    public void setStatuss(List<Integer> statuss) {
        this.statuss = statuss;
    }
}