package com.presto.api.user.entity;

import com.presto.common.dao.BaseEntity;
import java.util.List;

/**
 * 邀请码
 *
 * Auto Generated by <code>CodeGenerator</code>
 */
public class InviteCode extends BaseEntity {
    private static final long serialVersionUID = 1L;
    private String code;//
    private Integer status;//0-正常；1-废弃
    transient private List<Integer> statuss;//0-正常；1-废弃

    /**
     * return 
     */
    public String getCode() {
        return code;
    }

    /**
     * @param code 
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * return 0-正常；1-废弃
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * @param status 0-正常；1-废弃
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * return 0-正常；1-废弃s
     */
    public List<Integer> getStatuss() {
        return statuss;
    }

    /**
     * @param statuss 0-正常；1-废弃
     */
    public void setStatuss(List<Integer> statuss) {
        this.statuss = statuss;
    }
}