package com.presto.api.user.entity;

import com.presto.common.dao.BaseEntity;
import java.math.BigDecimal;
import java.util.List;

/**
 * 充值items
 *
 * Auto Generated by <code>CodeGenerator</code>
 */
public class RechargeItem extends BaseEntity {
    private static final long serialVersionUID = 1L;
    private BigDecimal rmbAmount;//人民币金额
    private BigDecimal amount;//书币金额
    private Integer status;//状态:0-新建;1-正常
    transient private List<Integer> statuss;//状态:0-新建;1-正常

    /**
     * return 人民币金额
     */
    public BigDecimal getRmbAmount() {
        return rmbAmount;
    }

    /**
     * @param rmbAmount 人民币金额
     */
    public void setRmbAmount(BigDecimal rmbAmount) {
        this.rmbAmount = rmbAmount;
    }

    /**
     * return 书币金额
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * @param amount 书币金额
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * return 状态:0-新建;1-正常
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * @param status 状态:0-新建;1-正常
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * return 状态:0-新建;1-正常s
     */
    public List<Integer> getStatuss() {
        return statuss;
    }

    /**
     * @param statuss 状态:0-新建;1-正常
     */
    public void setStatuss(List<Integer> statuss) {
        this.statuss = statuss;
    }
}