package com.presto.api.plantBook.entity;

import com.presto.common.dao.BaseEntity;
import java.util.List;

/**
 * 植书申请表
 *
 * Auto Generated by <code>CodeGenerator</code>
 */
public class PlantBookReq extends BaseEntity {
    private static final long serialVersionUID = 1L;
    private Long userId;//
    private Integer status;//状态:0,新建；1，审批通过；2，审批不通过
    transient private List<Integer> statuss;//状态:0,新建；1，审批通过；2，审批不通过
    private Integer plantType;//植书类型：0-赠与平台（书籍归平台所有）；1-分享到平台（平台代管书籍）；2-个人分享者（书籍自己管理）
    private Integer plantMethod;//植书方式：0，扫码植书；1，搜索植书；2，手工植书
    private Long bookId;//关联b_books书库表，扫码植书和搜索植书用到
    private String bookName;//书名,手工植书用到
    private String bookAuthor;//书作者,手工植书用到
    private String bookPress;//出版社，手工植书用到
    private String bookIsbn;//isbn号，手工植书用到
    private String bookImgUrl;//书籍封面，手工植书用到

    /**
     * return 
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * @param userId 
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * return 状态:0,新建；1，审批通过；2，审批不通过
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * @param status 状态:0,新建；1，审批通过；2，审批不通过
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * return 状态:0,新建；1，审批通过；2，审批不通过s
     */
    public List<Integer> getStatuss() {
        return statuss;
    }

    /**
     * @param statuss 状态:0,新建；1，审批通过；2，审批不通过
     */
    public void setStatuss(List<Integer> statuss) {
        this.statuss = statuss;
    }

    /**
     * return 植书类型：0-赠与平台（书籍归平台所有）；1-分享到平台（平台代管书籍）；2-个人分享者（书籍自己管理）
     */
    public Integer getPlantType() {
        return plantType;
    }

    /**
     * @param plantType 植书类型：0-赠与平台（书籍归平台所有）；1-分享到平台（平台代管书籍）；2-个人分享者（书籍自己管理）
     */
    public void setPlantType(Integer plantType) {
        this.plantType = plantType;
    }

    /**
     * return 植书方式：0，扫码植书；1，搜索植书；2，手工植书
     */
    public Integer getPlantMethod() {
        return plantMethod;
    }

    /**
     * @param plantMethod 植书方式：0，扫码植书；1，搜索植书；2，手工植书
     */
    public void setPlantMethod(Integer plantMethod) {
        this.plantMethod = plantMethod;
    }

    /**
     * return 关联b_books书库表，扫码植书和搜索植书用到
     */
    public Long getBookId() {
        return bookId;
    }

    /**
     * @param bookId 关联b_books书库表，扫码植书和搜索植书用到
     */
    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    /**
     * return 书名,手工植书用到
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * @param bookName 书名,手工植书用到
     */
    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    /**
     * return 书作者,手工植书用到
     */
    public String getBookAuthor() {
        return bookAuthor;
    }

    /**
     * @param bookAuthor 书作者,手工植书用到
     */
    public void setBookAuthor(String bookAuthor) {
        this.bookAuthor = bookAuthor;
    }

    /**
     * return 出版社，手工植书用到
     */
    public String getBookPress() {
        return bookPress;
    }

    /**
     * @param bookPress 出版社，手工植书用到
     */
    public void setBookPress(String bookPress) {
        this.bookPress = bookPress;
    }

    /**
     * return isbn号，手工植书用到
     */
    public String getBookIsbn() {
        return bookIsbn;
    }

    /**
     * @param bookIsbn isbn号，手工植书用到
     */
    public void setBookIsbn(String bookIsbn) {
        this.bookIsbn = bookIsbn;
    }

    /**
     * return 书籍封面，手工植书用到
     */
    public String getBookImgUrl() {
        return bookImgUrl;
    }

    /**
     * @param bookImgUrl 书籍封面，手工植书用到
     */
    public void setBookImgUrl(String bookImgUrl) {
        this.bookImgUrl = bookImgUrl;
    }
}